#This is K8 test
---
#hello this is swathi
#hello world
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "demo"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "demoapp"
  namespace: "default"
  labels:
    app: "demoapp"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "demoapp"
  template:
    metadata:
      labels:
        app: "demoapp"
    spec:
      containers:
      - name: "clouddemo"
        image: BUYERSPORTALUI_IMAGE
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "demoapp-hpa-bg9h"
  namespace: "default"
  labels:
    app: "demoapp"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "demoapp"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80

# ---
# apiVersion: "v1"
# kind: "Service"
# metadata:
#   name: "demoapp-service"
#   namespace: "default"
#   labels:
#     app: "demoapp"
# spec:
#   clusterIP: 10.199.160.227
#   clusterIPs:
#   - 10.199.160.227
#   externalTrafficPolicy: Cluster
#   ipFamilies:
#   - IPv4
#   ipFamilyPolicy: SingleStack
#   ports:
#   - nodePort: 31490
#     port: 8080
#     protocol: TCP
#     targetPort: 8080
#   selector:
#     app: demoapp
#   sessionAffinity: None
#   type: LoadBalancer
# status:
#   loadBalancer:
#     ingress:
#     - ip: 35.232.20.173

---
  apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "demoapp-service"
    namespace: "default"
    labels:
      app: "demoapp"
  spec:
    ports:
    - protocol: "TCP"
      port: 8080
    selector:
      app: "demoapp"
    type: "LoadBalancer"
    loadBalancerIP: ""
